### ISSUE TITLE
Humble Bundle plugin doesn't work anymore

### ISSUE THREAD

**Issue by hightower5** [UncleGoogle/galaxy-integration-humblebundle#166] opened 2021-12-21 13:28 UTC
The old version humblebundle_0.5.1 doesn't list any games anymore, and the new version humblebundle_0.9.5 crashes on login.

[plugin-humble.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7755661/plugin-humble.log)

**Comment by UncleGoogle** [comment] 2021-12-23 22:54
@hightower5 can you create separate issue for crashes with relevant logs? From the current one I see the 0.5.1 stuff only. Currently I have no easy access to Windows OS to check myself.

**Comment by hightower5** [comment] 2021-12-25 10:13
The humble log-file is empty. Here is a part of GalaxyClient.log
[GalaxyClient.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/7775699/GalaxyClient.log)

**Comment by UncleGoogle** [comment] 2021-12-27 21:30
@hightower5 could you follow this instruction to gather some clues? https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/155#issuecomment-800666512

**Comment by hightower5** [comment] 2021-12-28 12:19
I don't understand what I'm doing, but please.

```
C:\Users\hightower\AppData\Local\GOG.com\Galaxy\plugins\installed\humblebundle_0.9.5>"C:\Program Files (x86)\GOG Galaxy\python\python.exe" -c "import sys; sys.path.append('.'); import plugin; plugin.main()"

Unbehandelte Ausnahme: System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Users\hightower\AppData\Local\GOG.com\Galaxy\plugins\installed\humblebundle_0.9.5\modules\Python.Runtime.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515) ---> System.NotSupportedException: Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   bei System.Reflection.Assembly.LoadFrom(String assemblyFile)
   bei clrModule.PyInit_clr()
```

**Comment by UncleGoogle** [comment] 2021-12-28 21:14
@hightower5 thanks. Looks like the issue is a duplicate of #155 

I have no idea why for some people it happen, but looks like the issue caused by Windows security settings when ZIP is downloaded: https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres

Try:
1. remove plugin; download from Galaxy (in case you've downloaded it from github)
2. use this workaround https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/155#issuecomment-803114839

**Comment by hightower5** [comment] 2021-12-28 22:05
Hi unclegoogle,

the workaround helps. 

Thank you and best regards

tom

**Closed** 2021-12-28 22:48 UTC
Labels: bug

**Comment by UncleGoogle** [comment] 2021-12-28 23:00
@hightower5 could you check which .NET versions you have installed? https://www.windowscentral.com/how-quickly-check-net-framework-version-windows-10#dotnet_version_filexplorer

**Comment by hightower5** [comment] 2021-12-28 23:10
Tomorrow, I've shutdown my PC.😉

**Comment by hightower5** [comment] 2021-12-29 10:21
.NET Framework ver. 4.8.04084

**Comment by UncleGoogle** [comment] 2021-12-30 21:30
Thanks, that may help in reproduction.
