### ISSUE TITLE
Owned games not fetched (after plugin update by Galaxy)

### ISSUE THREAD

**Issue by NocturneBlock** [UncleGoogle/galaxy-integration-humblebundle#62] opened 2019-11-25 13:37 UTC
**Describe the bug**
Literally minutes after adding the integration, I installed A Slow Year as a test of how the integration works- the direct to the download worked fine, I downloaded and installed the game. Galaxy recognized the install, and I now had a "Play" button. Upon pressing it, I got the message at the bottom of the window that a Humble game was being started, but after a few seconds, it went away, and nothing further happened.

To check to see if this was an error with the game itself, I navigated to where I had installed it and ran it directly. It worked fine.

**Expected behavior**
Upon clicking "Play" on an installed game that Galaxy recognizes as installed, game is started.

**Plugin installed**
directly from Galaxy

**Provide logs**
Just so you know, GitHub throws an error if you try to attach a 7z file directly to this issue input area. Not sure if they support uploading them later.

[logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3886834/logs.zip)

**Comment by NocturneBlock** [comment] 2019-11-25 13:42
Huh. After some time and a Galaxy restart, both this and the issue I was having where Uninstall did nothing have gone away. So... Going to leave this open so you see it and can look at the logs, but it's working now.

**Comment by UncleGoogle** [comment] 2019-11-25 21:37
Hey! Thanks for reaching me out with detailed issue.

This is very interesting and sounds buggy on plugin side. It should work just after game detection, but somehow local_games cache do not contain the game_id you have tried to launch/uninstall. I've prepared version with detailed logging. Could you please try to reproduce with the same game? All steps:
[more_logging.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3888849/more_logging.zip)

- uninstall this game
- disconnect plugin
- Exit Galaxy (shouldn't be live in tray)
- make sure in manifest.json file in plugin directory (at %localappdata%\GOG.com\Galaxy\plugins\installed\humble_something), the version is 0.5.3 (Galaxy may remove all files on start in case of update to lastest version)
- unpack files I've send you to plugin directory 
    - this should ask about overwriting 2 files -> yes
- relaunch Galaxy, connect plugin
- install
- launch
- send me your logs

Thanks!

**Comment by UncleGoogle** [comment] 2020-01-07 20:53
It has happened to me yesterday just after autoupdate by Galaxy. Restarting Galaxy helps. I'm not sure, but probably just after plugin update, Galaxy forgets to ask about owned games belonging to user. Workaround is to ensure plugin will always ask humble API w/o needed to be requested by Galaxy.

**Comment by NocturneBlock** [comment] 2020-01-13 16:10
Sorry I didn't get back on this for a while. It appears that the version is 0.5.4. now. I am going to do the rest as you have said, let me know if I should have waited for a new version of the files you sent.

**Comment by UncleGoogle** [comment] 2020-01-13 16:56
Hey, dont worry. Let us wait for 6.0.0 because mechanics will be changed a bit.

**Comment by UncleGoogle** [comment] 2020-03-08 14:36
Should be fixed now

**Closed by UncleGoogle** 2020-03-08 14:36 UTC
Labels: bug
