### ISSUE TITLE
Wrong download link for Drm Free games

### ISSUE THREAD

**Issue by Bertaz** [UncleGoogle/galaxy-integration-humblebundle#71] opened 2019-12-14 18:11 UTC
**Describe the bug**
Trying to install Starbound from galaxy brings up the download page with the wrong ttl & t parameters. I guess those are identification keys for my account

**Expected behavior**
Open the correct download link

**Plugin installed**
directly from Galaxy

**Provide logs**
[plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3964148/plugin-humble-f0ca3d80-a432-4d35-a9e3-60f27161ac3a.log)
[GalaxyClient.log](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3964150/GalaxyClient.log)

**Comment by UncleGoogle** [comment] 2019-12-14 19:13
Hi, thanks for report. I havn't this game so I need your help for better understanding there is the problem. Please replace plugin.py with this file: 
[plugin.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3964243/plugin.zip) and repeat a download. Then upload logs

What are ttl & t parameters? 
What url is open and what is expected?

**Comment by Bertaz** [comment] 2019-12-15 01:52
> What are ttl & t parameters?

I meant url parameters
> What url is open and what is expected?

I didn't put them in the issue, cause I'm not sure if they are private data or not. The one from the integration gives a 403 Access Denied
Starbound download link taken from web page:
https://dl.humble.com/chucklefish/starbound_1.4.4_win32_win64.zip?gamekey=Kmccb2SppZyv7yq2&ttl=1576431275&t=e4abb9f8f7659300c7768af1acb68fbf
Given by integration:
https://dl.humble.com/chucklefish/starbound_1.4.4_win32_win64.zip?gamekey=Kmccb2SppZyv7yq2&ttl=1576324641&t=b7fe78f673ec71ebeba1c0cec2067905

For another game (Slipstream) the urls are different, but both work
Web page:
https://dl.humble.com/noctet_studio_q1EfT/slipstream-windows-v1.1.11a.zip?gamekey=nKMHmDbRakMVC5SC&ttl=1576436156&t=c93f6a4e61357a9eb504a200c9f3a2da
Integration:
https://dl.humble.com/noctet_studio_q1EfT/slipstream-windows-v1.1.11a.zip?gamekey=nKMHmDbRakMVC5SC&ttl=1576457671&t=34236116bbf8a889946cbfa082806504
> Please replace plugin.py with the file unpacked from this zip:
> [plugin.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3964243/plugin.zip) and repeat a download. Then upload logs 

[plugin-humble-logs.zip](https://github.com/UncleGoogle/galaxy-integration-humblebundle/files/3964533/plugin-humble-logs.zip)
With this version of plugin.py the parameters for Starbound remained the same, while Slipstream changed
https://dl.humble.com/noctet_studio_q1EfT/slipstream-windows-v1.1.11a.zip?gamekey=nKMHmDbRakMVC5SC&ttl=1576461069&t=e49b143f22b9ce667e2c4c0943ea75c0

**Comment by UncleGoogle** [comment] 2019-12-15 19:31
Thanks for info. I'll try to research the issue deeply in this week. Maybe HB changed sth in the flow, or I need to set cookies when signing for download. Will see.

**Comment by UncleGoogle** [comment] 2020-04-02 20:42
Does it still occur? Currently I have no Trove subscription to check.

**Comment by Bertaz** [comment] 2020-04-24 13:40
> Does it still occur? Currently I have no Trove subscription to check.

Yes it does.
Starbound:
Integration gives 403: https://dl.humble.com/chucklefish/starbound_1.4.4_win32_win64.zip?gamekey=Kmccb2SppZyv7yq2&ttl=1587551684&t=06cef10fff1632561dbf94c6b096cf00
Working link from humble library: https://dl.humble.com/chucklefish/starbound_1.4.4_win32_win64.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587820061&t=c45ed25d5624f846f147b28499cf35fe
I even mixed the two with the new `key` parameter, but the `ttl` & `t` parameters are still wrong. Returns 403: https://dl.humble.com/chucklefish/starbound_1.4.4_win32_win64.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587551684&t=06cef10fff1632561dbf94c6b096cf00

Slipstream:
Changed links, but both works
Integration: https://dl.humble.com/noctet_studio_q1EfT/slipstream-windows-v1.1.11a.zip?gamekey=nKMHmDbRakMVC5SC&ttl=1587819981&t=3402142482f822ee979cab20ced4d395
Humble library link: https://dl.humble.com/noctet_studio_q1EfT/slipstream-windows-v1.1.11a.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587820688&t=582ac332a5ed656250e9ae1ea51083aa

Hacknet (I have purchased this game and have it also from the trove)
Integration drm-free returns 403:
https://dl.humble.com/Hacknet_v5.069B_Standalone_WIN.zip?gamekey=F5nuzHHxq7veWWMG&ttl=1587551684&t=195bdd1c6fc86758f8849cb9869e3efa
Link from the trove works:
https://dl.humble.com/Hacknet_v5.069B_Standalone_WIN.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587820907&t=68a3f07e254465dd4e9db3d01e8f8b12
Link from humble library also works:
https://dl.humble.com/Hacknet_v5.069B_Standalone_WIN.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587820966&t=86364a2c41dde6b0349a6b0cb39999b7
The integration (with all game types checked) tries to download from the library. If I select only the trove the link works, but is different from the one the web trove gives:
https://dl.humble.com/Hacknet_v5.069B_Standalone_WIN.zip?key=ahFzfmhyLWh1bWJsZWJ1bmRsZXIRCxIEVXNlchiAgNCsosLCCww&ttl=1587821575&t=b8fafa170252e7c66d7f4ad94c5d8edc

**Comment by UncleGoogle** [comment] 2020-04-25 19:23
Hm, I'm almost sure that the issue is duplicate of #94 

I've wrote:
> For the drm-free games it works, but the links are different from the web ones. They have the gamekey parameter, not the key one.
Also if I select drm-free in the config (alone or with trove and keys) it works showing only drm-free games.

From the log above I can see that Starbound is drm-free game, not trove.

Galaxy deduplicates the same titles and you can switch between drm-free and trove or any other game instance bought from different platform from game view (icon on the top, cannot find now). So if you have both copies from store/bundle AND trove, you may think game is from Trove but clicking Install triggers drm-free download you've bought.

**Comment by Bertaz** [comment] 2020-04-25 23:52
> From the log above I can see that Starbound is drm-free game, not trove.

Yes, both Starbound and Slipstream are drm free games. So this issue isn't about trove games
> Hm, I'm almost sure that the issue is duplicate of #94

I agree, if the solution in #94 applies to my case (I think so), close this one
> Galaxy deduplicates the same titles and you can switch between drm-free and trove or any other game instance bought from different platform from game view (icon on the top, cannot find now). So if you have both copies from store/bundle AND trove, you may think game is from Trove but clicking Install triggers drm-free download you've bought.

Yeah, I noticed that. Am I correct in saying that, if I select only trove games in the integration options, the `Install` button tries to download from the trove?

**Comment by UncleGoogle** [comment] 2020-04-26 08:20
Yes, Install should get from trove then. 

So im closing the issue. Note that fix is not released yet. Will do in this week

**Closed** 2020-04-26 08:21 UTC
Labels: bug, help wanted
